# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: MILUV
description: A Multi-UAV Indoor Localization dataset with UWB and Vision

baseurl: "" # the subpath of your site, e.g. /blog
url: ""

github_username: decargroup
email: mohammed.shalaby@mail.mcgill.ca

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

domain: decargroup.github.io
url: https://decargroup.github.io/miluv/

color_scheme: dark

# Exclude from processing.
exclude: ['README.md', '.sass-cache/', '.jekyll-cache', 'gemfiles', 'Gemfile', 'Gemfile.lock', 'node_modules/', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/']

defaults:
  - scope:
      path: "docs"
      type: "posts"
      usemathjax: true
    values:
      layout: "default"


nav_enable: true

markdown: kramdown
